### ISSUE TITLE
Dask tasks not being shared among workers

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#788] opened 2020-09-24 14:09 UTC
I have a puzzling situation that is one of these difficult full-stack problems (not clear which package is responsible), so I'm posting it in our generic pangeo issue tracker.

The basic problem is contained in this dashboard screenshot. A single worker has all the tasks. That worker is out of memory, so the computation is stalled. The other workers are doing nothing. The only way out is to interrupt.

<img width="1773" alt="dask_stalled" src="https://user-images.githubusercontent.com/1197350/94155890-7493c680-fe4d-11ea-828d-9e8eedb0dede.png">

This problem can be reproduced on https://us-central1-b.gcp.pangeo.io/ with the following code

```python
from dask_gateway import Gateway
gateway = Gateway()
options = gateway.cluster_options()
options.worker_memory = 10
cluster = gateway.new_cluster(options)
cluster.adapt(minimum=1, maximum=30)

from dask.distributed import Client
client = Client(cluster)

import gcsfs
import dask.array as dsa
gcs = gcsfs.GCSFileSystem(requester_pays=True)
url = 'pangeo-scratch/paigem//paigem/CESM_POP_hires_control/SHF_2_target.zarr'
target_mapper = gcs.get_mapper(url)
target_array = dsa.from_zarr(target_mapper)

target_array.mean(axis=0).compute()
```

I am a bit lost on how to debug this. Is it a problem with distributed? Gateway? With my code?

Any tips would be appreciated. @TomAugspurger is of course the guru on this stuff.

cc @paigem

**Comment by mrocklin** [comment] 2020-09-24 15:59
Congratulations!  You have discovered a secret dashboard page!  Please proceed to `/stealing` to claim your prize!

**Comment by TomAugspurger** [comment] 2020-09-24 15:59
Hmm, it just finished well for me on us-central1-b.gcp.pangeo.io. 
I never had a single worker end up with too much memory. I wonder if there were more ready nodes in the kubernetes cluster, so my Dask cluster scaled up faster, and I never got into a bad situation?

I wonder if work stealing isn't kicking in here, since the task is actively running in that worker (https://distributed.dask.org/en/latest/work-stealing.html#transactional-work-stealing).

**Comment by chiaral** [comment] 2020-09-24 16:10
I've had this issue - tasks concentrating in one worker and stalling - many many times in my workflow. It is different from Ryan's because it is a very intensive calculation.

In particular, in my case:
1) I don't necessarily run out of memory for the overwhelmed worker. It just simply gets stuck with hundreds of tasks and it doesn't go anywhere.
2) it can stall for hours, so I have to babysit my runs to avoid it stalls for like days. it won't die.
3) I sort of solved by increasing worker memory of a lot, but at some point it still reaches this situation (almost like if it were leaking memory, but at some point we checked and we didn't see this), and I just have to kill the job, and re start it (my workflow allows for restarting without losing everything, because I am looping tru years of data one at the time and save them one at the time). 
4) my graphs are really big >50k tasks , but nothing gets overwhelmed or out of memory, until ... it does 🤷🏼‍♀️
5) some times.. it gets over the hump... 
6) this issue started when we went from dask kubernetis to dask gateway. I am positive that I did not have this specific issue before that upgrade.

**Comment by TomAugspurger** [comment] 2020-09-24 16:15
Thanks for the additional info. I was able to reproduce by lowering the worker memory limit. I'll continue to debug this, and will keep in mind that it's happening elsewhere.

**Comment by chiaral** [comment] 2020-09-24 16:15
FYI [Here](https://github.com/pangeo-data/pangeo-cloud-federation/issues/657) a picture of my dask dashboard when it reaches the stalling. It's a busy graph, for sure.

**Comment by rabernat** [comment] 2020-09-24 16:19
> Hmm, it just finished well for me on us-central1-b.gcp.pangeo.io.
> I never had a single worker end up with too much memory. I wonder if there were more ready nodes in the kubernetes cluster, so my Dask cluster scaled up faster, and I never got into a bad situation?

Frustrating that you could not replicate it. That's unfortunately often the case. Indeed, on a fresh cluster, I was also unable to reproduce, including when I limited to `maximum=10` workers.

**Just read latest comments**

> Thanks for the additional info. I was able to reproduce by lowering the worker memory limit. I'll continue to debug this, and will keep in mind that it's happening elsewhere.

Ok, if we can reproduce, then we are in business! Often the solution to these problems is "just increase your memory." But in this case it seems a little more pathological.

> Congratulations! You have discovered a secret dashboard page! Please proceed to `/stealing` to claim your prize!

🤣 Thanks Matt! It's always exciting to get to the next level of the Dask game!

**Comment by dcherian** [comment] 2020-09-24 16:40
Some documentation/tips on debugging this kind of situation would be useful. 

I've run into some version of this and didn't know what to do... or where to look.

**Comment by rabernat** [comment] 2020-09-24 17:06
> I've run into some version of this and didn't know what to do... or where to look.

I would go so far as to say that **this** [gestures wildly at the general problem] is one of the central problems facing Pangeo and limiting us from having the impact we want. If you and I are getting stuck regularly, imagine how a first-year grad student feels!

**Comment by dcherian** [comment] 2020-09-24 17:37
I agree; we need a few 5-10 minutes youtube videos on "dask performance debugging techniques at scale".

**Comment by TomAugspurger** [comment] 2020-09-24 18:56
I'll be sure to record something once I'm able to understand the issue.

Right now it's looking like an issue with the worker's state machine. The
scheduler says it's processing a bunch of tasks, but the worker's `ready`
and `exeucting` stacks are both empty.

I accidentally killed my scheduler so I'll need to reproduce it again (took
me ~10ish attempts to get the cluster stuck earlier).

**Comment by TomAugspurger** [comment] 2020-09-24 21:00
Actually, more likely a comms issue. The scheduler sends a message to the worker like "compute this <thing>!" and the worker logs "I got this new <thing> to work on!".

Looking through the logs / scheduler state, `<thing>` is set to `processing` (scheduler told the worker to do it) but the worker never says "I got <thing>"`.

Looking in `Scheduler.worker_comms[worker]`, I see the BatchedComm has 1,326 pending messages.

**Comment by TomAugspurger** [comment] 2020-09-24 21:10
And this managed to kick off the computation again.

```python
async def drain(dask_scheduler):
    res = await dask_scheduler.stream_comms[worker]._background_send()
    return res

fut = client.run_on_scheduler(drain)
```

So something fishing is going on in `BatchedSend`.

**Comment by mrocklin** [comment] 2020-09-25 14:17
> I would go so far as to say that this [gestures wildly at the general problem] is one of the central challenges facing Pangeo and limiting us from having the impact we want. If you and I are getting stuck regularly, imagine how a first-year grad student feels!

Given that, I wonder if the next time Pangeans apply for grant that funding for solving problems like this should be included as part of that grant.

**Comment by rabernat** [comment] 2020-09-25 17:45
> Given that, I wonder if the next time Pangeans apply for grant that funding for solving problems like this should be included as part of that grant.

I think the reason we have not done this so far is that we don't have a clear vision for exactly how to address this challenge.

**Comment by rabernat** [comment] 2020-09-25 17:48
I also want to repeat how singularly valuable @TomAugspurger has become in this area. Through attending our meetings regularly, learning about the science questions, and helping deploy the infrastructure, Tom is perhaps the closest thing we have to a full-stack Pangeo engineer. His ability to get to the bottom of real problems is unparalleled.

But I'm not sure how to scale it. If I could clone Tom, I would. A better question I guess is, how do we train more people like Tom.

**Comment by mrocklin** [comment] 2020-09-25 20:25
(sorry to hijack this thread)

> I think the reason we have not done this so far is that we don't have a clear vision for exactly how to address this challenge.

Do you mean from a technical or an administrative perspective?  Technically, there seem to be several different challenges, many of which we probably can't anticipate.  When we wrote the original grant we solved this by saying a few things that were important, but leaving enough wiggle room that we were able to explore lots of other things as they came up (including side projects, like cloud deployments ;) )

Administratively, historically Pangeo funded companies like Anaconda with chunks of grants to do technical work.  The original Pangeo grant was about 1/3 focused towards software engineering efforts by professional software engineers.

> I also want to repeat how singularly valuable @TomAugspurger has become in this area. Through attending our meetings regularly, learning about the science questions, and helping deploy the infrastructure, Tom is perhaps the closest thing we have to a full-stack Pangeo engineer. His ability to get to the bottom of real problems is unparalleled.

> But I'm not sure how to scale it. If I could clone Tom, I would. 

Totally agreed.  One might ask how we got Tom in the first place.  Tom worked for an OSS software company that had deep expertise in these problems.  He was brought on to handle a few technical issues at first.  As he became more comfortable and engaged he took on more and more responsibility, and eventually took the lead.  You can't clone Tom, but you can grow more of him.

> A better question I guess is, how do we train more people like Tom?

Yeah, my recommendation would be to allocate some money to some OSS company that generally knows how to solve these problems.  I'm obviously biased here, but trying hard to keep my for-profit hat away I think that having Pangeo further engage with the OSS maintainers would be a good thing for pangeo, providing that that engagement comes with actual money that allows for non-volunteer time to be spent solving hard problems.

**Comment by mrocklin** [comment] 2020-09-25 20:30
I wrote a response earlier but then decided that it probably crosses a for-profit / open source line.  My apologies, I've deleted it.  In general, I encourage well funded groups asking for help with Dask to support professional paid developers working on Dask to help them solve their problems.

**Comment by rabernat** [comment] 2020-09-25 20:48
Matt I really appreciate your thoughts on this.

I think the pattern of using grant money to support private companies to do this type of work has been very effective for Pangeo.

Currently Pangeo is in a transition from its first generation of NASA / NSF grants to new sources of funding. So there are new opportunities on the horizon for this sort of collaboration.

**Comment by TomAugspurger** [comment] 2020-09-25 21:33
Back to the "how would a user debug this" question: regular users on pangeo's jupyterhubs don't have access to the stdout of the scheduler or worker pods. I'm guessing this is somewhat common.

I have kubectl access so I can see the output on the scheduler:

```
dask_gateway.dask_cli - INFO - Requesting scale to 30 workers from 1
distributed.batched - ERROR - Error in batched write
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/batched.py", line 93, in _background_send
    payload, serializers=self.serializers, on_error="raise"
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/comm/tcp.py", line 241, in write
    stream.write(b)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/iostream.py", line 553, in write
    self._write_buffer.append(data)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/iostream.py", line 177, in append
    b += data  # type: ignore
BufferError: Existing exports of data: object cannot be re-sized
```

which would have made things easier to pinpoint. `client.get_scheduler_logs()` only gets the logs from the `distributed.scheduler`, not all the logs from the *schedulers process* (which show up in stdout on the pod). 

If you know a bit about logging / distributed, you can configure things

```python
import logging

def setup_logging(dask_scheduler):
    handler = dask_scheduler._deque_handler
    logger = logging.getLogger("distributed")
    logger.addHandler(handler)
    logger.warning("test")
```

so that any call to a logger in `distributed` on the scheduler will be added to the scheduler's log.

I'll think about how we can make this easier for users (in addition to thinking about the cause of the comm error).

**Comment by TomAugspurger** [comment] 2020-10-09 13:41
https://github.com/dask/distributed/pull/4135 is merged and deployed to us-central1-b.gcp.pangeo.io/. So I'm going to consider it fixed until we see more issues (there might be some semi-related issues linked from https://github.com/dask/distributed/pull/4128 about workers connections, especially when rapidly scaling up).

**Closed by TomAugspurger** 2020-10-09 13:41 UTC

**Comment by dcherian** [comment] 2020-10-09 13:53
Thanks Tom!
