### ISSUE TITLE
problem with xarray.DataArray.values

### ISSUE THREAD

**Issue by Chiara7** [pangeo-data/pangeo#392] opened 2018-09-21 13:52 UTC
Hello all, 
I am Janjenka Chiara, a student from the German Potsdam Institute of Climate Impact Research and I am working with Pangeo. I am working with the ocean data set 'pangeo-data/cm2.6/one_percent/temp_salt_u_v-5day_avg/', and since Wednesday and error occured while I used the command 'values' on an xarray.DataArray (see the example below). Before Wednesday I could use the command without getting an error. It would be really helpful if you could have a look at it at this minimal example and maybe help me solving my issue. Thank you very much!

```python
#import packages
import xarray as xr
from dask.distributed import Client, progress
from dask_kubernetes import KubeCluster
cluster = KubeCluster(n_workers=40)
client = Client(cluster)

#load data
import gcsfs
gcsmap = gcsfs.mapping.GCSMap('pangeo-data/cm2.6/one_percent/temp_salt_u_v-5day_avg/')
ds = xr.open_zarr(gcsmap, decode_cf=True, decode_times=False)

#example that does not work
mimi = ds.v.isel(time=0)
mimi = mimi.isel(st_ocean=slice(0,2))
mimi = mimi.sel(xu_ocean=slice(-20, -19.5),yu_ocean=slice(-34,-33.8))

mimi.values
```
the stack trace:
```python
distributed.core - ERROR - 'text'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/distributed/core.py", line 320, in handle_comm
    result = yield result
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/conda/lib/python3.6/site-packages/distributed/scheduler.py", line 2191, in gather
    who_has, rpc=self.rpc, close=False, serializers=serializers)
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/conda/lib/python3.6/site-packages/distributed/utils_comm.py", line 67, in gather_from_workers
    r = yield c
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/conda/lib/python3.6/site-packages/distributed/worker.py", line 2808, in get_data_from_worker
    max_connections=max_connections)
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1113, in run
    yielded = self.gen.send(value)
  File "/opt/conda/lib/python3.6/site-packages/distributed/core.py", line 448, in send_recv
    raise Exception(response['text'])
KeyError: 'text'

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-6-805c5e90ca1d> in <module>()
      3 mimi = mimi.sel(xu_ocean=slice(-20, -19.5),yu_ocean=slice(-34,-33.8))
      4 
----> 5 mimi.values

/opt/conda/lib/python3.6/site-packages/xarray/core/dataarray.py in values(self)
    403     def values(self):
    404         """The array's data as a numpy.ndarray"""
--> 405         return self.variable.values
    406 
    407     @values.setter

/opt/conda/lib/python3.6/site-packages/xarray/core/variable.py in values(self)
    385     def values(self):
    386         """The variable's data as a numpy.ndarray"""
--> 387         return _as_array_or_item(self._data)
    388 
    389     @values.setter

/opt/conda/lib/python3.6/site-packages/xarray/core/variable.py in _as_array_or_item(data)
    209     TODO: remove this (replace with np.asarray) once these issues are fixed
    210     """
--> 211     data = np.asarray(data)
    212     if data.ndim == 0:
    213         if data.dtype.kind == 'M':

/opt/conda/lib/python3.6/site-packages/numpy/core/numeric.py in asarray(a, dtype, order)
    499 
    500     """
--> 501     return array(a, dtype, copy=False, order=order)
    502 
    503 

/opt/conda/lib/python3.6/site-packages/dask/array/core.py in __array__(self, dtype, **kwargs)
   1254 
   1255     def __array__(self, dtype=None, **kwargs):
-> 1256         x = self.compute()
   1257         if dtype and x.dtype != dtype:
   1258             x = x.astype(dtype)

/opt/conda/lib/python3.6/site-packages/dask/base.py in compute(self, **kwargs)
    154         dask.base.compute
    155         """
--> 156         (result,) = compute(self, traverse=False, **kwargs)
    157         return result
    158 

/opt/conda/lib/python3.6/site-packages/dask/base.py in compute(*args, **kwargs)
    400     keys = [x.__dask_keys__() for x in collections]
    401     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 402     results = schedule(dsk, keys, **kwargs)
    403     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    404 

/opt/conda/lib/python3.6/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, **kwargs)
   2191             try:
   2192                 results = self.gather(packed, asynchronous=asynchronous,
-> 2193                                       direct=direct)
   2194             finally:
   2195                 for f in futures.values():

/opt/conda/lib/python3.6/site-packages/distributed/client.py in gather(self, futures, errors, maxsize, direct, asynchronous)
   1566             return self.sync(self._gather, futures, errors=errors,
   1567                              direct=direct, local_worker=local_worker,
-> 1568                              asynchronous=asynchronous)
   1569 
   1570     @gen.coroutine

/opt/conda/lib/python3.6/site-packages/distributed/client.py in sync(self, func, *args, **kwargs)
    651             return future
    652         else:
--> 653             return sync(self.loop, func, *args, **kwargs)
    654 
    655     def __repr__(self):

/opt/conda/lib/python3.6/site-packages/distributed/utils.py in sync(loop, func, *args, **kwargs)
    275             e.wait(10)
    276     if error[0]:
--> 277         six.reraise(*error[0])
    278     else:
    279         return result[0]

/opt/conda/lib/python3.6/site-packages/six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None

/opt/conda/lib/python3.6/site-packages/distributed/utils.py in f()
    260             if timeout is not None:
    261                 future = gen.with_timeout(timedelta(seconds=timeout), future)
--> 262             result[0] = yield future
    263         except Exception as exc:
    264             error[0] = sys.exc_info()

/opt/conda/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1097 
   1098                     try:
-> 1099                         value = future.result()
   1100                     except Exception:
   1101                         self.had_exception = True

/opt/conda/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1105                     if exc_info is not None:
   1106                         try:
-> 1107                             yielded = self.gen.throw(*exc_info)
   1108                         finally:
   1109                             # Break up a reference to itself

/opt/conda/lib/python3.6/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1472 
   1473             else:  # ask scheduler to gather data for us
-> 1474                 response = yield self.scheduler.gather(keys=keys)
   1475 
   1476             if response['status'] == 'error':

/opt/conda/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1097 
   1098                     try:
-> 1099                         value = future.result()
   1100                     except Exception:
   1101                         self.had_exception = True

/opt/conda/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1105                     if exc_info is not None:
   1106                         try:
-> 1107                             yielded = self.gen.throw(*exc_info)
   1108                         finally:
   1109                             # Break up a reference to itself

/opt/conda/lib/python3.6/site-packages/distributed/core.py in send_recv_from_rpc(**kwargs)
    552             try:
    553                 comm = yield self.live_comm()
--> 554                 result = yield send_recv(comm=comm, op=key, **kwargs)
    555             except (RPCClosed, CommClosedError) as e:
    556                 raise e.__class__("%s: while trying to call remote method %r"

/opt/conda/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1097 
   1098                     try:
-> 1099                         value = future.result()
   1100                     except Exception:
   1101                         self.had_exception = True

/opt/conda/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1111                             exc_info = None
   1112                     else:
-> 1113                         yielded = self.gen.send(value)
   1114 
   1115                     if stack_context._state.contexts is not orig_stack_contexts:

/opt/conda/lib/python3.6/site-packages/distributed/core.py in send_recv(comm, reply, serializers, deserializers, **kwargs)
    444     if isinstance(response, dict) and response.get('status') == 'uncaught-error':
    445         if comm.deserialize:
--> 446             six.reraise(*clean_exception(**response))
    447         else:
    448             raise Exception(response['text'])

/opt/conda/lib/python3.6/site-packages/six.py in reraise(tp, value, tb)
    690                 value = tp()
    691             if value.__traceback__ is not tb:
--> 692                 raise value.with_traceback(tb)
    693             raise value
    694         finally:

/opt/conda/lib/python3.6/site-packages/distributed/core.py in handle_comm()
    318                         if type(result) is gen.Future:
    319                             self._ongoing_coroutines.add(result)
--> 320                             result = yield result
    321                     except (CommClosedError, CancelledError) as e:
    322                         if self.status == 'running':

/opt/conda/lib/python3.6/site-packages/tornado/gen.py in run()
   1097 
   1098                     try:
-> 1099                         value = future.result()
   1100                     except Exception:
   1101                         self.had_exception = True

/opt/conda/lib/python3.6/site-packages/tornado/gen.py in run()
   1105                     if exc_info is not None:
   1106                         try:
-> 1107                             yielded = self.gen.throw(*exc_info)
   1108                         finally:
   1109                             # Break up a reference to itself

/opt/conda/lib/python3.6/site-packages/distributed/scheduler.py in gather()
   2189 
   2190         data, missing_keys, missing_workers = yield gather_from_workers(
-> 2191             who_has, rpc=self.rpc, close=False, serializers=serializers)
   2192         if not missing_keys:
   2193             result = {'status': 'OK', 'data': data}

/opt/conda/lib/python3.6/site-packages/tornado/gen.py in run()
   1097 
   1098                     try:
-> 1099                         value = future.result()
   1100                     except Exception:
   1101                         self.had_exception = True

/opt/conda/lib/python3.6/site-packages/tornado/gen.py in run()
   1105                     if exc_info is not None:
   1106                         try:
-> 1107                             yielded = self.gen.throw(*exc_info)
   1108                         finally:
   1109                             # Break up a reference to itself

/opt/conda/lib/python3.6/site-packages/distributed/utils_comm.py in gather_from_workers()
     65             for worker, c in coroutines.items():
     66                 try:
---> 67                     r = yield c
     68                 except EnvironmentError:
     69                     missing_workers.add(worker)

/opt/conda/lib/python3.6/site-packages/tornado/gen.py in run()
   1097 
   1098                     try:
-> 1099                         value = future.result()
   1100                     except Exception:
   1101                         self.had_exception = True

/opt/conda/lib/python3.6/site-packages/tornado/gen.py in run()
   1105                     if exc_info is not None:
   1106                         try:
-> 1107                             yielded = self.gen.throw(*exc_info)
   1108                         finally:
   1109                             # Break up a reference to itself

/opt/conda/lib/python3.6/site-packages/distributed/worker.py in get_data_from_worker()
   2806                                    deserializers=deserializers,
   2807                                    op='get_data', keys=keys, who=who,
-> 2808                                    max_connections=max_connections)
   2809         if response['status'] == 'OK':
   2810             yield comm.write('OK')

/opt/conda/lib/python3.6/site-packages/tornado/gen.py in run()
   1097 
   1098                     try:
-> 1099                         value = future.result()
   1100                     except Exception:
   1101                         self.had_exception = True

/opt/conda/lib/python3.6/site-packages/tornado/gen.py in run()
   1111                             exc_info = None
   1112                     else:
-> 1113                         yielded = self.gen.send(value)
   1114 
   1115                     if stack_context._state.contexts is not orig_stack_contexts:

/opt/conda/lib/python3.6/site-packages/distributed/core.py in send_recv()
    446             six.reraise(*clean_exception(**response))
    447         else:
--> 448             raise Exception(response['text'])
    449     raise gen.Return(response)
    450 

KeyError: 'text'

​```

**Comment by mrocklin** [comment] 2018-09-21 13:56
Welcome @Chiara7 !

Can you verify that the following runs for you without erring?

    client.get_versions(check=True)

**Comment by rabernat** [comment] 2018-09-21 14:00
@Chiara7: based on our email conversations, I developed the following example notebook for you that shows how to calculate the meridional overturning streamfunction in the South Atlantic. Hopefully this will help you move forward:

https://gist.github.com/rabernat/727dbdce7e31d326a4543f892d6f11f5

In general, I would recommend reviewing the xarray documentation and tutorial (https://github.com/pangeo-data/pangeo-tutorial-sea-2018) in order to familiarize yourself more with how to structure your analysis. You might also want to look at [xgcm](https://xgcm.readthedocs.io/en/latest/), which I use in my notebook to simplify some operations.

**Comment by rabernat** [comment] 2018-09-21 14:53
I think the problem is due to a recent upgrade I made to pangeo.pydata.org. I updated to chart version `0.1.1-a8f057f`, which has the following lines in `worker-template.yaml`.
```
    image: pangeo/notebook:92c4bfd
```

https://github.com/pangeo-data/helm-chart/blob/master/docker-images/notebook/worker-template.yaml

@apatlpo and others are experiencing this exact same issue. I peeked at @apatlpo's environment and saw that `worker-template.yaml` was not updated. So we need to figure out what is going on. I thought that the new docker image would automatically overwrite it.

**Comment by rabernat** [comment] 2018-09-21 15:09
Here is what happened.

In pangeo-data/helm-chart#65, I updated the notebook docker image to point to a different worker image. Chartpress successfully built the image in PR mode:
https://travis-ci.org/pangeo-data/helm-chart/builds/429680410
(but because it was a PR, it did not deploy, i.e. push to dockerhub)

When that PR was merged, chartpress should have re-built the image, tagged it, and pushed it to dockerhub. For some reason, this didn't happen:
https://travis-ci.org/pangeo-data/helm-chart/builds/422259394

It would be great if @yuvipanda or @dsludwig could take a look at this. It is fairly urgent, as pangeo.pydata.org dask clusters are basically broken now. I have a crazy busy day today, and I really don't have time to sort this out myself.

**Comment by rabernat** [comment] 2018-09-21 15:14
or @jacobtomlinson

**Comment by rabernat** [comment] 2018-09-21 15:37
see https://github.com/pangeo-data/helm-chart/issues/68

**Comment by rabernat** [comment] 2018-09-21 15:55
Everything should be fixed now.

**Comment by Chiara7** [comment] 2018-09-21 16:36
Yes, the problem is solved, everything does work again. Thank you very much for your great and very fast help!

**Comment by rabernat** [comment] 2018-09-22 01:35
@Chiara7 - please feel free to open further issues as you move forward with your project. We are very happy to help.

**Closed by rabernat** 2018-09-22 01:35 UTC
