### ISSUE TITLE
Educational events on Pangeo resources

### ISSUE THREAD

**Issue by mrocklin** [pangeo-data/pangeo#440] opened 2018-10-22 16:15 UTC
Hello educator!

We're pleased to hear that you're interested in using Pangeo's cloud deployments for an educational event.  To make sure that things run smoothly we ask that you post the following information here *before* your event:

-  The date and time of the event
-  Information about the event.  Is it part of a conference or university bootcamp?  What is the general topic?
-  A link to the binder or other materials that you intend to use
-  The number of people that you expect to attend, and the resources required per attendee (in terms of number of cores or memory)

This helps us both by ensuring that the cluster is sufficiently large during your event (otherwise your students may not get as many cores as they expect) and by providing us information to give back to our funding agencies about how their resources benefit the public.

### Edit

For educators wishing to use this cluster, you may want to pre-allocate a bunch of VMs before your students arrive.  This will make sure that VMs are around when they try to log on.  Otherwise they might have to wait a few minutes while Google gives us machines.

Typically I do this by logging into a Jupyter notebook, and then allocating a fairly large cluster.  To do this I need to overwrite the default maximum number of allowed workers.

```python
dask.config.set({'kubernetes.count.max': 1000})
cluster.scale(1000)
# wait a bit until they arrive
cluster.scale(0) # release the pods back to the wild, the VMs should stick around for a bit
```

This forces the worker node pool to grow, and then those workers stick around for a bit.  It may take a while for the cloud to give us enough machines.  I would do this at least 30m before the tutorial start, and possibly an hour before.  You can track progress by watching the IPython widget output of `KubeCluster`, which should update live.

You definitely want torelease the pods back to the wild before the tutorial starts, but not too soon before, otherwise the cloud provider will clean up the VMs.  Maybe run `scale(0)` a minute before things start off (but in practice you should have 10-20 minutes grace period here).

**Comment by mrocklin** [comment] 2018-10-22 16:18
I used binder.pangeo.io to present a tutorial at PyData NYC on 2018-10-22.  My apologies for including this late.  Requested information:

-  **Date and time:** 2018-10-22 between 3pm-5pm
-  **Information about the event**: This was a general Dask tutorial at [PyData NYC 2018](https://pydata.org/nyc2018/)
-  **Link to materials:** We used these materials: https://github.com/mrocklin/pydata-nyc-2018-tutorial
-  **Number of attendees and resources per attendee:** There are about 200 attendees.  Their exercises are designed with about 20 cores in mind.

**Comment by xhochy** [comment] 2018-10-22 17:01
I would like to use binder.pangeo.io to present a Dask tutorial at PyCon.DE on 2018-10-24. Requested information:

- **Date and time:** 2018-10-24 between 14:00 and 15:30 CEST, 8am - 9:30am US Eastern time
- **Information about the event:** This will be a general Dask tutorial at PyCon.DE 2018
- **Link to materials:** We plan to use these materials: https://github.com/mrocklin/pydata-nyc-2018-tutorial
- **Number of attendees and resources per attendee:** Around 25 attendees. Their exercises are designed with about 20 cores in mind.

**Comment by rabernat** [comment] 2018-10-22 17:08
Thanks for doing this Matt!

**Comment by TomAugspurger** [comment] 2018-10-23 14:31
I would like to use binder.pangeo.io to present a Dask tutorial at ODSC West on 2018-11-01.
Requested information:

* **Date and time**: 2018-11-01 between 09:00 - 11:00 Pacific time (12:00 - 2:00 Eastern)
* **Information about the event**: This will be a general Dask tutorial at [ODSC West](https://odsc.com/training/portfolio/cloud-native-data-science-with-dask)
* **Link to materials**: https://github.com/TomAugspurger/dask-tutorial-odsc-2018
* **Number of attendees and resources per attendee**: Will update

I'm also happy to set up the infrastructure separately from the pangeo binder. This would mostly just be if you want additional testers of the binder infrastructure to work out issues.

**Comment by mrocklin** [comment] 2018-10-24 12:41
During @xhochy 's tutorial we again ran into resourcing problems.  This time the worker node pool did not expand to its full capacity.  I'm not sure why.  To resolve this I allocated all of the non-preemptible nodes I could (arond 500 cores) for the duration of the tutorial.  

There was also some concern when first starting up notebooks and clusters.  It's awkward to have the notebook sit idle waiting for workers for a few minutes while VMs start up.  Educators might want to ask for many VMs just before class by creating a very large cluster (for example a cluster with 1000 workers).  We intentionally make this difficult to do by adding a limit to dask-cluster size.  You can override this limit with the following code:

```python
with dask.config.set({'kubernetes.count.max': 1000}):
    cluster.scale(1000)
```

**Comment by TomAugspurger** [comment] 2018-10-25 16:01
@rabernat, @mrocklin would you appreciate additional beta testers of this setup? If so I'll start to ensure my materials for the tutorial next week work on the binder infrastructure.

The tutorial is actually titled "Cloud Native Data Science with Dask", so I plan to spend about 20 minutes walking through the how the clusters were actually deployed for the attendees.

**Comment by jhamman** [comment] 2018-10-25 18:51
@TomAugspurger - Please go ahead as planned and use binder.pangeo.io. We're still learning how our binderhub handles these events so if you don't mind being a beta tester, we'd appreciate the pressure. I think @dsludwig and I will be working on the deployment over the next week a bit but we'll keep things in a stable state for the day of your tutorial.

**Comment by TomAugspurger** [comment] 2018-11-01 22:31
Pretty much perfectly.. It was about 40 people, and I the Dask workers came up instantly for people.

I didn't watch to see if / how scaling down went.

**Comment by mrocklin** [comment] 2018-11-01 22:53
For background, just before this workshop happened I logged in and scaled up to 1000 workers, and then back down again. To do this I had to break the built-in worker limit by setting a config parameter

```python
dask.config.set({'kubernetes.count.max': 1000})
cluster.scale(1000)
# wait a bit
cluster.scale(0)
```

This forces the worker node pool to grow, and then those workers stick around for a bit.

**Comment by mrocklin** [comment] 2018-11-01 23:00
I also had to force things to scale down manually.  We still have the problem of fluentd, prometheus, and some other small pod keeping the worker-pool nodes awake.

**Comment by mmccarty** [comment] 2018-11-08 17:36
I would like to use binder.pangeo.io to present a Dask tutorial at Capital One: C4ML on 12/13/18. Requested information:

- **Date and time:** 2018-12-13 between 1pm - 2:30pm US Eastern time
- **Information about the event:** This will be a general Dask tutorial at Capital One: C4ML
- **Link to materials:** We plan to use these materials: https://github.com/mrocklin/pydata-nyc-2018-tutorial
- **Number of attendees and resources per attendee:** 1 user + more watching. Their exercises are designed with about 20 cores in mind.  Due to connection constrains at C1, I'll probably just walk through the tutorial and share my screen.

**Comment by lesteve** [comment] 2018-11-14 06:45
I would like to use binder.pangeo.io to present a Dask tutorial at PyParis 2018 on 2018-11-15. Requested information:

    Date and time: 2018-11-15 between 10:45 and 12:15 CEST, 3:45am - 5:15am US Eastern time
    Information about the event: This will be a general Dask tutorial at PyParis 2018
    Link to materials: We plan to use these materials: mrocklin/pydata-nyc-2018-tutorial
    Number of attendees and resources per attendee: Around 50 attendees. Their exercises are designed with about 20 cores in mind.

**Comment by mrocklin** [comment] 2018-11-14 12:40
Thanks for the information @lesteve .  I recommend that you follow the procedure in https://github.com/pangeo-data/pangeo/issues/440#issuecomment-435213971 to ensure that there are some VMs provisioned when your students arrive.  I'll make sure that things spin down afterwards.

**Comment by jcrist** [comment] 2018-11-14 16:33
We (@martindurant and myself) would like to use binder.pangeo.io to present a Dask tutorial at PyData DC on Friday (Nov 16th) from 11:00 am - 12:30 pm EST. We plan to use these materials: https://github.com/mrocklin/pydata-nyc-2018-tutorial. I am unsure of the number of attendees, I have not been provided this information.

**Comment by mmccarty** [comment] 2018-11-14 16:59
@jcrist @martindurant Just to give you a ball park estimate.  The PyDataDC tutorials are sold out at 150 and there is only 1 other tutorial going on at that time.  I would plan for around 75.

**Comment by lesteve** [comment] 2018-11-16 14:12
Just a quick feed-back after the dask tutorial yesterday at PyParis. Running the dask tutorial through the pangeo binder setup went flawlessly, that was really impressive!

I asked to 1000 workers 15 minutes before the beginning of the tutorial waited until I got them (maybe 5-10 minutes I don't remember exactly) and then scaled down to zero. There were around 40 people and they were able to get their 20 workers instantly.

**Comment by guillaumeeb** [comment] 2018-12-03 16:10
I plan to use binder.pangeo.io to present a Dask tutorial at http://www.irt-saintexupery.com/. Requested information:

- Date and time: 2018-12-18 between 14:00 and 17:00 CET, 08:00am - 11:00am US Eastern time
- Information about the event: This will be a general Dask tutorial for a team working on Machine learning and remote sensing data
- Link to materials: We plan to use these materials: https://github.com/mrocklin/pydata-nyc-2018-tutorial
- Number of attendees and resources per attendee: Around 10 attendees. Their exercises are designed with about 20 cores in mind.

**Comment by jhamman** [comment] 2018-12-03 16:19
@rabernat, @scottyhq and I will be giving a Pangeo tutorial on 12/12 at the 2018 AGU Fall Meeting. (xref: #468).

- **Date and time:** 2018-12-12 between 8am - 12:30pm US Eastern time
- **Information about the event:** This will be a 4hr Pangeo tutorial at the AGU Fall Meeting
- **Link to materials:** We plan to use these materials: TBD
- **Number of attendees and resources per attendee:** Around 75 attendees. Their exercises are designed with about 20 cores in mind.

**Comment by darothen** [comment] 2019-01-06 02:47
I'll be giving a short (30-minute) tutorial during the AMS meeting. I don't expect very many (read: really, anyone) people to follow along, but it's still possible, so I want to record things here:

- *Date and time*: January 7, 2019 at 3-3:30 PM MDT
- *Information about the event*: I will give a short live demo of scaling an analysis from a test dataset on my laptop to running on a larger one (~25 GB) on the cloud
- *Link to materials*: TBD, plan on posting tomorrow
- *Number of attendees and resources per attendee*: I expect there to be ~25-50 people in the audience, and possibly 10 people who actively try to follow along. I will ask people not to use more than 10 cores.

**Comment by mrocklin** [comment] 2019-01-06 04:05
Users should feel free to use as many cores as we like (I think we cap them
at something like 50 or 100).  At that small size of audience I wouldn't
worry too much.

You may want to go through the procedure mentioned above where you allocate
a large cluster just before class just to make sure that there are some
workers around.  If you don't do this then users may have to wait a few
minutes before things spin up, but that should be ok too if you inform them
that that we're waiting for a few VMs to show up from Google.

**Comment by rabernat** [comment] 2019-01-16 09:49
FYI I will be doing an impromptu demo at Oxford in a few hours using Pangeo binder. Expect some traffic on the cluster, not sure how much.

**Comment by jakirkham** [comment] 2019-01-24 01:43
Was just looking at that. SGTM. Thanks. Should we add it to the OP?

Great, thanks @mrocklin. I think the students will find this really cool. :)

**Comment by mrocklin** [comment] 2019-01-24 06:13
> Was just looking at that. SGTM. Thanks. Should we add it to the OP?

Good idea.  Done!

**Comment by guillaumeeb** [comment] 2019-03-24 09:31
I'd like to use binder.pangeo.io to present a Dask tutorial for the [Observatoire Midi Pyrénées](http://www.obs-mip.fr/en) lab .

- Date and time: 2018-04-02 between 14:00 and 17:00 CET, 08:00am - 11:00am US Eastern time
- Information about the event: This will be a Pangeo tutorial for academics working on remote sensing data for earth sciences.
- Link to materials: Not sure, robably https://github.com/mrocklin/pydata-nyc-2018-tutorial and need to take a look at AGU tutorial from @rabernat and @jhamman.
- Number of attendees and resources per attendee: Around 25 attendees. Their exercises are designed with about 20 cores in mind.

**Comment by jcrist** [comment] 2019-04-01 19:24
I'd like to use binder.pangeo.io to present a Dask tutorial on April 3rd from 1:30 to 5:00 PM Central time at AnacondaCon. There will be ~100 attendees. I'm not quite done with materials yet, but these will be some combination of our PyCon tutorial (https://github.com/TomAugspurger/dask-tutorial-pycon-2018) and the PyData NYC tutorial (https://github.com/mrocklin/pydata-nyc-2018-tutorial). I'll update this comment with a link when the materials are finished.

**Comment by rabernat** [comment] 2019-04-02 19:27
@jcrist - 100 attendees each with their own `KubeCluster` could get pretty big! We have recently become more conscious of our cloud burn rate, which was unsustainably high for a while. 

Please go ahead with your tutorial. We want this resource to be used, especially for educational purposes. Just try to be conscientious about scale when you have 100 simultaneous users.

**Comment by jcrist** [comment] 2019-04-02 19:30
Thanks @rabernat. I've scaled down the cluster size to a max of 10 workers each (default for previous tutorials was 20), with fewer for simpler notebooks to try and combat this. I'm willing to go smaller to help conserve resources, I don't want to strain the cloud resources of such a useful community project.

**Comment by mrocklin** [comment] 2019-04-02 19:34
FWIW I think that these tutorials are valuable to drum up interest and my guess (though not very well informed at the moment) is that they're a small amount relative to general use, particularly because they're one-off rather than continuous.  I don't know though.

**Comment by rabernat** [comment] 2019-04-02 19:40
To be clear, I am 100% 👍 on the tutorial. I agree they have very high value.

It might be useful to use this as an opportunity to figure out how much these tutorials cost. People frequently ask me that, and I don't have an answer beyond "not very much."

Dask workers go into a nodepool with `n1-highmem-32` preemptible instances. These have 32 vCPUs and 208 GB of memory. They cost $0.40 per hour. We could make a back-of-the-envelope estimate and then verify from the logs after the tutorial.

**Comment by rabernat** [comment] 2019-04-02 19:43
btw, @jcrist - you might want to pop in on https://github.com/pangeo-data/pangeo-binder/issues/37 - @guillaumeeb is reporting that users at his tutorial are losing notebook. Could be because we are using preemptible node pools.

This could affect your tutorial tomorrow.

**Comment by guillaumeeb** [comment] 2019-04-02 19:45
Hi everyone, my tutorial today went pretty well, with public going from governemental agencies (CNES, Ifremer), spatial industry (CLS which is working on altimetry products), or labs (CESBIO for spatial imagery, Legos for Ocean, GET for earth science ...). 

I've encountered some small issues:
* https://github.com/pangeo-data/pangeo-binder/issues/37: Loosing connection to user notebooks at random, not sure why.
* https://github.com/pangeo-data/pangeo-example-notebooks/issues/31: Landsat example not working, problem with gdal install.

I think this repositories for tutorial are great, and we should find a way to maintain them. This is probably linked to #575. I'm talking about https://github.com/pangeo-data/pangeo-tutorial-agu-2018 and https://github.com/mrocklin/pydata-nyc-2018-tutorial.

**Comment by rsignell-usgs** [comment] 2019-04-03 13:10
@guillaumeeb would it be worth adding the mrocklin pydata tutorial to the list of tutorials at
https://github.com/pangeo-data/awesome-open-climate-science#tutorials
or was that mostly eclipsed by the AGU tutorial?      

We don't want to bombard people with too many similar tutorials (or worse, just old versions of basically the same tutorial), but if it takes a different or complementary approach, that should be summarized  and included in the awesome list, right?

**Comment by guillaumeeb** [comment] 2019-04-03 14:08
@rsignell-usgs just added it yesterday to https://github.com/pangeo-data/education-material. However, I don't think it is appropriate for a climate science use cases list.

But maybe these two lists are overlapping...

And I fully support the fact we don't want to have too many simular tutorial, but I think we do currently.

**Comment by mrocklin** [comment] 2019-04-03 18:53
It looks like binderhub has a config option that limits the number of users per repository.

```yaml
binderhub:
  config:
      per_repo_quota: 100
```

Larger tutorials might run into this.  We might want to change this number (or not) at some point (though preferably not within the next few hours).

**Comment by jhamman** [comment] 2019-04-03 20:58
@mrocklin - I'd be fine increasing this limit. If you or @jcrist can open an issue on pangeo-binder, we can discuss more there.

**Comment by jacobtomlinson** [comment] 2019-04-23 10:53
I'd like to use the binder deployment for two tutorials on the 1st and 2nd of May (a weekend). Will likely be around 10am GMT on each day for a couple of hours to an audience of 10-20 people. I'm intending on using the material @jcrist prepared for AnacondaCon.

**Comment by rsignell-usgs** [comment] 2019-04-23 16:19
Thanks for the tip to: https://github.com/jcrist/anacondacon-2019-tutorial

**Comment by robfatland** [comment] 2019-05-02 23:29
I'd like to use binder.pangeo.io to present a tutorial at 
[Northwest Data Science Summit](https://escience.washington.edu/northwest-data-science-summit/). 

* Date and time: 2019-05-08 between 14:00 and 15:30 PDT
* Pangeo tutorial for academics interested in data science in broad scope
* Material will be drawn from pangeo-data/pangeo-example-notebooks, likely Ryan's ocean height
* Expect 25 participants x 10 workers each?
* Suspect I'll need some help getting this right

**Comment by jhamman** [comment] 2019-05-03 17:43
@robfatland - sounds good. See @mrocklin's comments earlier in this thread for some tips on helping scale up/down your cluster efficiently.

**Comment by jmunroe** [comment] 2019-05-07 05:20
I'm doing a day-long workshop / training on Pangeo as part of C3DIS (Canberra).   I've got a Pangeo / BinderHub deployment set up on AWS but I would like to reserve binder.pangeo.io as a fallback in case my AWS deployment turns out to not scale.

Date and time: 2019-05-09 between 9 am and 5 pm AEST (after @robfatland training!)
Information about the event: Pangeo Tutorial at C3DIS, Canberra
Link to materials: We plan to use these materials: https://github.com/jmunroe/pangeo-tutorial-c3dis-2019 (rebranded from AGU 2018 tutorials)
Number of attendees and resources per attendee: 25 participants x 20 workers each.

**Comment by robfatland** [comment] 2019-05-08 04:28
As note also on slack: Practice run hitting a snag, here are details:

Ryan's sea level notebook running in binder is hanging fire on the cell below **Visually Examine Some Of The Data**. The prior **Initialize Dataset** cell ran fine. The KubeCluster cell runs but gives this error:

```
/srv/conda/lib/python3.6/site-packages/distributed/bokeh/core.py:57: UserWarning:
Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the diagnostics dashboard on a random port instead.
  warnings.warn('\n' + msg)
```

The dask task stream remains empty. Halp!

**Comment by guillaumeeb** [comment] 2019-05-08 05:19
@robfatland, you output traces are just warning and not errors, this should not prevent notebooks to work fine.

First one says your scheduler has started on another port because default one was used (which is to be expected during a tutorial). Have you tried opening the dashboard in another window ?

Second is juste a deprecation warning and should have non impact.

Does the cluster widget shows you allocated cores?

**Comment by robfatland** [comment] 2019-05-08 14:27
Tried again, anonymous browser. This is working. Initially I get **workers: 0 cores: 0 memory: 0**. Thinking this was incorrect I set Manual Scaling to 10 but later realized this is an unnecessary step if one is happy with the default 20 workers. Anyway now: The first user gets a pause while things fire up and then everything goes. My second user seems to fire up faster. 

And by the way this is just friggin' awesome.

**Comment by mrocklin** [comment] 2019-05-08 14:44
@robfatland I recommend priming the cluster with some VMs.  You may want to read the edit in the top post of this issue.

**Comment by rabernat** [comment] 2019-05-08 14:52
I think having some visualization of what the cluster is doing would go a long way towards alleviating user / instructor anxiety during these tutorials. I'm talking about a basic visual representation of the node / pod information that kubectl can provide. Ideally this could be a tab in Jupyterlab, much like the dask extension.

This is motivated by our experience with the dask dashboard. Users are happy to wait for things if they have feedback about what the computers are doing. But just waiting with no info / progress causes anxiety and confusion.

**Comment by mrocklin** [comment] 2019-05-08 14:55
There may already be a tool that helps to visualize what GCP or Kubernetes
are doing?  It might be worth raising that as a separate issue.

**Comment by rabernat** [comment] 2019-05-08 15:06
See https://discourse.jupyter.org/t/lab-extension-for-monitoring-kubernetes-cluster/1026

**Comment by robfatland** [comment] 2019-05-08 16:36
@mrocklin I have some softball noob questions on your procedure. 

Let's suppose I have 25 participants where each will allocate 20 workers by default from Ryan's excellent sea surface notebook; so I need 500 VMs. Suppose my talk is at 2pm but I won't get to the pangeo demo slide until 2:45... 

- When I log in to 'a Jupyter notebook': Do you intend specifically on the pangeo binder jupyter lab?
- dask.config and cluster.scale methods can be run from a notebook cell?
- I don't need any particular authentication for this? i.e. anybody could walk in off the street?
- Roughly when do I run these two lines? 
- How do I know I have waited long enough before running `cluster.scale(0)`?
- How long should those 1000 VMs persist for, ballpark? 

```
dask.config.set({'kubernetes.count.max': 1000})
cluster.scale(1000)
# wait a bit until they arrive
cluster.scale(0) 
# release the pods back to the wild, the VMs should stick around for a bit
```

**Comment by mrocklin** [comment] 2019-05-08 17:02
First, you mean 500 pods, not VMs.  The VMs given to us by the cloud service provider will be quite large.

> When I log in to 'a Jupyter notebook': Do you intend specifically on the pangeo binder jupyter lab?

No preference between notebook and lab

> dask.config and cluster.scale methods can be run from a notebook cell?

Yes, from any python environment

> I don't need any particular authentication for this? i.e. anybody could walk in off the street?

Correct.  Acknowledged that this is concerning :)  Currently Pangeo's binder deployment is entirely open access.

> Roughly when do I run these two lines?

Answered up top in a recent edit

> How do I know I have waited long enough before running cluster.scale(0)?

Same as above

> How long should those 1000 VMs persist for, ballpark?

Same as above

**Comment by robfatland** [comment] 2019-05-08 17:05
fantastic, thanks; I'll remark later on how it goes

**Comment by NickMortimer** [comment] 2019-05-10 03:22
Hi 

I'm doing a training session on Pangeo in Hobart on Monday 13th I'll have about 35 people and would be good to use binder.pangeo.io just wanted to check that would be ok.

**Comment by robfatland** [comment] 2019-05-10 19:47
@NickMortimer as noted above I failed to pre-heat the system for a talk. I have it as a self-action-item to retry this and try and understand the process better; but main point: Please see Matt Rocklin's **Edit** on the very top entry and I strongly advocate you practice pre-heat-and-run in advance of the session.

**Comment by robfatland** [comment] 2019-05-21 20:52
I'm *possibly* hosting 24 early-career oceanographers next week Tues - Friday. With @scottyhq 's assistance I set up a separate GitHub org called escience-pangeo where we can whitelist participants on an as-needed basis to the AWS-hosted pangeo JupyterHub. (Pls advise if we are missing any issues; the usage should not be too onerous / expensive.) 

I would like to revisit using Ryan's sea level notebook which operates on a 74GB dataset. (In fact the source data may be larger; but the sea level anomaly piece is 74GB). It runs now on binder on the Google cloud and the data is in the GCP pangeo-data bucket. So far so good; no egress gotcha; but using the pangeo AWS JHub as Scott suggests *will* incur $7 egress per go, give or take. 

We would save that fee by creating an S3 copy of the same data. Then the API call has to be modified in the notebook. @rabernat please advise when you have a sec.

**Comment by rsignell-usgs** [comment] 2019-05-23 18:32
@robfatland are you using the AWS JupterHub running in region `us-west-2` or `us-east-1`?

I'd also like to have a copy of this data in AWS also, if you don't have it already.   I'm ready to write the sea level data (258GB) from GCS to AWS S3 with this command, if you give the okay!

```
rclone sync gcloud:pangeo-data/dataset-duacs-rep-global-merged-allsat-phy-l4-v3-alt  aws-west:gcloud:pangeo-data/dataset-duacs-rep-global-merged-allsat-phy-l4-v3-alt --checksum --fast-list --transfers 16
```

**Comment by robfatland** [comment] 2019-05-23 19:15
Hi @rsignell-usgs 
Scott and I both say "ok". Further: Scott notes it is us-east-1 (nasa.pangeo.io) and there is a corresponding regional bucket pangeo-data-useast1 to use as destination. It is actually $0.12 / GB so we're looking at about $31 on the GCP account.

**Comment by pbranson** [comment] 2019-05-24 00:22
To avoid incurring the egress cost I have downloaded the altimetry data
from CMEMS and was going to convert to zarr, but it occurred to me that
possibly @rabernat may have done some additional preparation steps beyond a
simple conversion?

Given it is likely that future events are going to be ran in various
locations I wonder if it's possible to develop some data curation scripts
for the freely available datasets? (i.e the sea level data is from
marine.copernicus.eu I think)

These would likely be useful examples in their own right for
preparing/chunking zarr stores

Then people could prepare the data on available resources and distribute to
the relevant buckets/regions.

**Comment by guillaumeeb** [comment] 2019-05-24 22:05
Hey, I'm planning to do a Pangeo tutorial at CNES (with CNES people and collaborators like Mercator).

- Date and time: 2019-06-11 between 15:00 and 17:30 CET, 09:00am - 11:30am US Eastern time
- Information about the event: this will be a Pangeo tutorial for CNES scientists and CNES cluster users.
- Link to materials: https://github.com/pangeo-data/pangeo-tutorial, https://github.com/jcrist/anacondacon-2019-tutorial
- Number of attendees and resources per attendee: Around 30 attendees. 20 cores/person.

**Comment by rsignell-usgs** [comment] 2019-06-12 13:17
I'm planning to do a Pangeo live demo today between 1:30-2:30pm EDT.   I'm going to use the pangeo binder on AWS `us-west-2`: https://aws-uswest2-binder.pangeo.io/v2/gh/reproducible-notebooks/hurricane-ike-water-levels/master?filepath=hurricane_ike_water_levels.ipynb, with 30 workers (60 cores).     I'm not going to encourage the attendees to try it in real time, but tell them they can try it later.

**Comment by scottyhq** [comment] 2019-07-02 16:15
We're planning a Pangeo interactive tutorial Tuesday July 16 11:45 - 2:15 PST at the ESIP Summer meeting: https://sched.co/PtOj 

We'll be using the ESIP landsat demo on AWS us-west-2: https://github.com/scottyhq/esip-tech-dive/tree/aws-binder 

And possibly the pangeo tutorial materials on the Google Cloud Binder: https://github.com/pangeo-data/pangeo-tutorial

Anticipating about 20 participants, adaptive scaling with 1-5 workers per person.

**Comment by djhoese** [comment] 2019-07-02 17:11
I'm teaching a Satpy tutorial at SciPy 2019 on Monday July 8th from 8am to 12pm with a focus on everyone running everything locally. However, some users weren't so sure if their machines met my preferred/minimum requirements (8GB RAM, 4 cores) so I'm considering suggesting pangeo binder for the 0-3 people who may need it. The repository that will be loaded is [here](https://github.com/pytroll/tutorial-satpy-half-day).

NOTE: I haven't actually tested if all my examples will run on the binder without hitting memory limits.

**Comment by djhoese** [comment] 2019-07-24 17:40
I'm teaching a small 4 hour session to <15 high schoolers for an introduction to Python and Satpy on Thursday, August 8th during a day camp. This is probably the lightest workload I'll ever put on pangeo's binder, but since it is running Satpy and I may want to demonstrate other Pangeo examples I'd like to run it on pangeo's binder.

**Comment by jakirkham** [comment] 2019-09-23 05:41
Guessing this shouldn’t be marked as stale.

**Comment by jacobtomlinson** [comment] 2019-09-23 08:53
I've added the pinned label which the stale bot should ignore.

**Comment by cgentemann** [comment] 2020-02-16 17:36
- date and time: 2/17 3:30-4:00pmpm PT
- information:  AGU Ocean Sciences 2020
- link: https://tinyurl.com/rs4frer
- Resources:  60 people, 20 cores each

**Comment by cgentemann** [comment] 2020-02-16 17:37
- date and time: 2/27 10:00-11:00am PT
- information:  JPL workshop
- link: https://tinyurl.com/rs4frer
- Resources:  40 people, 20 cores each

**Comment by willirath** [comment] 2020-03-10 11:05
- date and time: 23 March 2020 afternoon CET
- information: 1-hour hands-on session as part of a [High-resolution Modeling for Climate and Weather Workshop](https://www.imk-tro.kit.edu/english/9906.php)
- link: TBA
- Resources: 20-30 people, 20 cores each

**Comment by dshean** [comment] 2020-03-13 20:15
March 13, 2020, 2:30-5:30 PM PDT (approximately 1 hour from now!)
UW Geospatial Data Analysis course
https://github.com/UW-GDA (course material to be released in coming month)
14 undergrad/grad students

This is our last class of the quarter.  We've mostly focused on smaller datasets/problems thus far, as I'm emphasizing basic approaches and concepts.  But I'd like to at least expose them to scaling with dask, as some may need for their final projects and future research.  

I'm planning to have all students launch pangeo binder on aws us-west-2 and work through some of the sample notebooks.  I'll probably have the students stick with local clusters for now, but I may try to do a demo with kubecluster for the LS8 notebook.

I wish I had seen these AGU 2019 materials sooner, they are excellent!  Thanks to @scottyhq for last-minute advice.  Will plan to connect and integrate earlier next year.

**Comment by mktippett** [comment] 2020-09-07 19:48
- 9/8/2020 11:30am-1pm
- First class demo. ENSO is the general topic.
- https://binder.pangeo.io/v2/gh/mktippett/ENSO-math/master
- 10-15 users.  

Just now it took 21 minutes to start. Maybe I'm doing it wrong. 

Thanks!

**Comment by mmccarty** [comment] 2021-04-07 16:00
- 4/7/2021 6:00-9pm
- Guest Lecture at GWU: dask-tutorial
- https://github.com/dask/dask-tutorial
- ~10 users.

**Comment by jhamman** [comment] 2023-12-15 17:07
This was a great issue but is not longer how AGU resources are being coordinated. Thanks all who participated here.

**Closed by jhamman** 2023-12-15 17:07 UTC
Labels: pinned
