### ISSUE TITLE
Problems with loading data correctly

### ISSUE THREAD

**Issue by lufiedl** [pangeo-data/pangeo#693] opened 2019-08-15 13:15 UTC
Hello everyone,
I'm Lukas, a Bachelor student at Potsdam Institute for Climate Impact Research. In a way I'm continuing @chiara7 's work with PANGEO.
I have a question concerning the data, wich is loaded into the Jupyter Notebook. I wanted to add two different data sets from the GFDL_CM_2.6 catalog, but when comparing the data (e.g. the sea surface temperature) they seem to be identical. I'm pretty sure that this is my fault. Could you help me? I will attach a code example. 

[Example of the problem.pdf](https://github.com/pangeo-data/pangeo/files/3505605/Example.of.the.problem.pdf)

I am new to GitHub so please excuse me for the unconventional way of posting this issue.
Thank you in advance for your help!

**Comment by rabernat** [comment] 2019-08-15 15:47
@lufiedl - you are doing everything correctly! The problem is a typo in our catalog record, which I have fixed in https://github.com/pangeo-data/pangeo-datastore/pull/45. Once that pull-request is merged and the catalog updated, it should work fine.

As a little background here, the raw data is stored in [zarr](https://zarr.readthedocs.io) format on Google Cloud Storage in a bucket called `pangeo-data`. If you have a google cloud account, you should be able to browse it directly here: https://console.cloud.google.com/storage/pangeo-data

In order to make the data more easily accessible, we use an [intake catalog](https://intake.readthedocs.io/en/latest/). This catalog lives in this github repo: https://github.com/pangeo-data/pangeo-datastore/tree/master/intake-catalogs. The entries in the intake catalog point to locations in google cloud storage. In this case, there was a typo in the intake catalog, and both entries (`GFDL_CM2_6_control_ocean_3D` and `GFDL_CM2_6_one_percent_ocean_3D`) were pointing to the same underlying dataset. That's what I fixed in https://github.com/pangeo-data/pangeo-datastore/pull/45.

Thanks for your patience as we iron out the kinks in this new way of working. We would love to learn more about your project and get your feedback on how pangeo is working for you.

**Closed** 2019-08-15 15:59 UTC

**Comment by rabernat** [comment] 2019-09-04 14:44
Hi @lufiedl - we're trying to optimize the costs on ocean.pangeo.io. We have noticed some patterns where there might be a big opportunity for savings.

Is it possible that you doing the following at the beginning of all of your notebooks?
```python
from dask.distributed import Client, progress
from dask_kubernetes import KubeCluster
cluster = KubeCluster(n_workers=40)
```

What this does is to allocate 40 worker pods to you and just keep them running. From the logs, it appears that these workers are spending the vast majority of their time idle, accruing costs without actually doing any work.

An alternative pattern would be to use [`cluster.adapt()`](https://kubernetes.dask.org/en/latest/api.html#dask_kubernetes.KubeCluster.adapt) to auto-scale your cluster elastically. That way, we only pay for the compute we actually need.

I'd be happy to speak with you and help figure out the optimal usage patterns for whatever you are trying to do. As I stated in my previous message:
> We would love to learn more about your project and get your feedback on how pangeo is working for you.

This is a very new and experimental approach.

**Comment by lufiedl** [comment] 2019-09-05 13:02
Hi,
I was not sure how to communicate with you all efficiently. 
I will definitely implement the lines you mentioned and I will give my best to keep the costs as low as possible.

I am using pangeo to study an anti-correlation between the SST's of the Labrador Sea and the Arctic Ocean. And so far the tool is working absolutely fine. I did not have a lot of experience in coding when I started my Bachelors project but pangeo made it easy for me get into the topic. Also @chiara7 made my beginning with pangeo very smooth. 
At the moment I am trying to plot some time series using the model years, but I have some problems with the `nc_time_axis` that apparently is required. 
So I'm learning something new about pangeo and jupyter notebooks every day, also with the help of  this GITHUB page. 

Sorry, that I let you wait with my answer. I would to be in contact with you more regularly.. :)

**Comment by rabernat** [comment] 2019-09-05 13:10
No problem! Thanks a lot for the information--very useful to know!

If you are using auto-scaling, you will experience some delays (up to a few minutes) for your cluster to scale up.

> I was not sure how to communicate with you all efficiently.

This is a problem for the project. We use GitHub for most communication, but that's not very familiar to many scientists. We are experimenting with a new forum (https://discourse.pangeo.io), but it is not really launched yet.

In the meantime, you are always welcome at our weekly meetings: http://pangeo.io/meeting-notes.html

**Comment by lufiedl** [comment] 2019-09-07 10:49
Dear @rabernat, I have some problems implementing the auto-scaling option. Could you give me an example on how to do this? I am sorry for bothering you because of this.

**Comment by TomAugspurger** [comment] 2019-09-07 11:23
@lufiedl ideally it's 

```python
cluster = KubeCluster()
cluster.adapt(maximum=10)  # or however many you need
```

When you `compute` a result Dask will notice that it doesn't have free resources and start up some workers (which will take some time. Usually a few minutes).

Let us know if your having issues with that, and we can take a look at the logs.

**Comment by lufiedl** [comment] 2019-09-07 11:52
Thank you @TomAugspurger, that worked very well. I did experience the loading time but after some 5 to 10 minutes it began to calculate. Is there a restriction of the number of workers I am allowed to use? Is 10 the maximum or can I take a maximum of 40 for example?

**Comment by TomAugspurger** [comment] 2019-09-07 12:20
40 (or many more) should be just fine. I’m not sure if this Pangeo deployment has a max.
